ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
obj-y := hwmsen_helper.o
obj-$(CONFIG_LGE_SENSOR_UNIFIED_NODE) += lge_sensors_sysfs.o
